baseURL = "https://rootsec1.github.io/"
title = "Abhishek Murthy"
theme = "hugo-coder"
languageCode = "en-us"
defaultcontentlanguage = "en"
contentDir = "content"
pluralizelisttitles = false

paginate = 50

[markup.highlight]
    style = "github-dark"

[params]
    author = "Abhishek Murthy"
    info = "software engineer (backend + infra) obsessed with security."
    description = "Abhishek's blog"
    keywords = "blog,developer,personal"
    avatarurl = "/images/avatar.png"
    enableTwemoji = true
    colorScheme = "auto"
    hidecolorschemetoggle = false
    footerContent = "If you're so smart, why are you unhappy?"
    dateFormat = "January 2, 2006"
    favicon_16 = "/images/favicon-16x16.png"
    favicon_32 = "/images/favicon-32x32.png"
    touchIcon = "/images/apple-touch-icon.png"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/rootsec1/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/abhishekwl/"
[[params.social]]
    name = "BlinkIt"
    icon = "fa fa-globe fa-2x"
    weight = 3
    url = "https://blinkit.com/blog/first-12-months-blinkit-abhishek-m"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 4
    url = "https://twitter.com/_rootsec1"

# Menu links
[[menu.main]]
    name = "about"
    weight = 1
    url = "about/"
[[menu.main]]
    name = "posts"
    weight = 2
    url  = "posts/"
[[menu.main]]
    name = "my bookmarks"
    weight = 5
    url  = "bookmarks/"
